# Generated by Django 3.2.6 on 2021-08-10 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DistMiner', '0004_auto_20210810_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exuser',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='exuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 1, 24, 16, 874874, tzinfo=utc)),
        ),
    ]
