# Generated by Django 3.2.6 on 2021-08-10 01:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DistMiner', '0008_auto_20210810_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 1, 31, 23, 937116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exuser',
            name='token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
