# Generated by Django 3.2.6 on 2021-08-10 02:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DistMiner', '0016_alter_exuser_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 2, 8, 56, 982160, tzinfo=utc)),
        ),
    ]
