# Generated by Django 3.2.6 on 2021-08-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DistMiner', '0018_alter_exuser_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pc',
            old_name='token',
            new_name='user',
        ),
    ]
